name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Build Angular
        run: npm run build

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permissão ao Gradle
        run: chmod +x android/gradlew

      - name: Gerar APK Debug
        run: cd android && ./gradlew assembleDebug

      - name: Enviar APK como artifact
        uses: actions/upload-artifact@v4
        with:
          name: EcoTotally-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk