import { Injectable, signal, computed } from '@angular/core';

export type Lang = 'pt-BR' | 'en-US' | 'es-ES';

const PREFS_KEY = 'eco_prefs';
const LANG_KEY  = 'eco_lang';

// ─────────────────────────────────────────────────────────────
// Dicionário global – todas as páginas do app
// ─────────────────────────────────────────────────────────────
const DICT: Record<Lang, Record<string, string>> = {
  'pt-BR': {
    // bottom-nav
    nav_home:        'Início',
    nav_consumo:     'Consumo',
    nav_simular:     'Simular',
    nav_graficos:    'Gráficos',
    nav_insights:    'Insights',
    nav_mapa:        'Mapa',
    nav_config:      'Config',

    // menu
    menu_hi:         'Olá,',
    menu_impact:     'Seu impacto, em tempo real',
    menu_updated:    'Atualizado automaticamente a cada 10s.',
    menu_consumos:   'Consumos',
    menu_simulacoes: 'Simulações',
    menu_gasto:      'Gasto total acumulado',
    menu_metas:      'Metas',
    menu_ver_todas:  'Ver todas →',
    menu_sem_meta:   'Nenhuma meta criada',
    menu_sem_meta_sub: 'Defina limites de gastos e acompanhe seu progresso',
    menu_atalhos:    'Atalhos',
    menu_tile_consumo:   'Consumo',
    menu_tile_consumo_s: 'Registre seus gastos',
    menu_tile_metas:     'Metas',
    menu_tile_metas_s:   'Defina limites',
    menu_tile_simular:   'Simular',
    menu_tile_simular_s: 'Calcule impactos',
    menu_tile_graficos:  'Gráficos',
    menu_tile_graficos_s:'Visualize tendências',
    menu_tile_insights:  'Insights',
    menu_tile_insights_s:'Recomendações IA',
    menu_tile_mapa:      'Mapa',
    menu_tile_mapa_s:    'Pontos de reciclagem',
    menu_tile_perfil:    'Perfil',
    menu_tile_perfil_s:  'Editar dados',

    // consumo page
    con_title:       'Consumo',
    con_subtitle:    'Registre e acompanhe seus consumos.',
    con_tipo:        'Tipo',
    con_gasto:       'Gasto (R$)',
    con_data:        'Data',
    con_meta:        'Vincular a uma meta',
    con_meta_opt:    'opcional',
    con_sem_meta:    '— Sem meta vinculada —',
    con_metas_tipo:  'Metas de',
    con_outras_metas:'Outras metas',
    con_sem_metas_msg:'Nenhuma meta cadastrada ainda. Crie em Metas 🎯',
    con_add_btn:     '+ Adicionar consumo',
    con_hist:        'Histórico',
    con_vazio:       'Nenhum consumo registrado ainda.\nCrie o primeiro acima ☝️',

    // configurações
    settings:        '⚙️ Configurações',
    subtitle:        'Personalize sua experiência no EcoTotally.',
    profile:         'Perfil',
    viewProfile:     'Ver meu perfil',
    appearance:      '🎨 Aparência',
    appDesc:         'Escolha como o app deve ser exibido.',
    light:           'Claro',
    dark:            'Escuro',
    system:          'Sistema',
    reduceAnim:      'Reduzir animações',
    notifications:   '🔔 Notificações',
    alertsLabel:     'Alertas de consumo e metas',
    preferences:     '🌐 Preferências',
    language:        'Idioma',
    energyUnit:      'Unidade de energia',
    dataReports:     '📄 Dados e relatórios',
    dataDesc:        'Baixe seu relatório completo em PDF ou limpe o cache local.',
    downloadPdf:     '📄 Baixar relatório (PDF)',
    generatingPdf:   'Gerando PDF…',
    clearCache:      '🧹 Limpar cache do app',
    about:           'ℹ️ Sobre',
    version:         'Versão',
    support:         'Suporte',
    privacy:         'Política de privacidade',
    terms:           'Termos de uso',
    view:            'Ver',
    account:         '🚪 Conta',
    logout:          'Sair da conta',
    themeUpdated:    'Tema atualizado.',
    reportDownloaded:'Relatório baixado com sucesso.',
    cacheCleared:    'Cache limpo.',
    confirmCache:    'Limpar dados em cache do app? Suas configurações serão mantidas, mas você pode precisar entrar de novo.',
    // páginas principais
    g_title: 'Gráficos',
    g_subtitle: 'Visualize consumos e simulações por categoria.',
    g_consumos_tab: '📊 Consumos',
    g_simulacoes_tab: '⚡ Simulações',
    g_empty_consumos: 'Sem consumos ainda. Cadastre alguns para ver os gráficos.',
    g_total_geral: 'Total geral',
    g_registros: 'registros',
    g_por_categoria: 'Por categoria',
    g_tendencia_mensal: 'Tendência mensal',
    g_empty_simulacoes: 'Sem simulações ainda. Crie em Simulação ⚡',
    g_custo_total_simulado: 'Custo total simulado',
    g_simulacoes: 'simulações',
    g_por_tipo: 'Por tipo',
    meta_title: 'Metas',
    meta_subtitle: 'Defina limites de gastos e acompanhe o progresso em tempo real.',
    meta_new_aria: 'Nova meta',
    meta_edit: 'Editar meta',
    meta_new: 'Nova meta',
    meta_close_aria: 'Fechar formulário',
    meta_tipo: 'Tipo',
    meta_objetivo: 'Valor objetivo (R$)',
    meta_inicio: 'Início',
    meta_fim: 'Fim',
    meta_save: '💾 Salvar meta',
    meta_empty: 'Nenhuma meta criada ainda.',
    meta_empty_sub: 'Crie a primeira no botão + 👆',
    meta_edit_aria: 'Editar meta',
    meta_delete_aria: 'Excluir meta',
    meta_days_left: 'd restantes',
    meta_acumulado: 'Acumulado',
    meta_objetivo_label: 'Objetivo',
    meta_over: '⚠️ Meta estourada em',
    meta_attention: '🟡 Atenção: faltam',
    meta_to_limit: 'para o limite',
    meta_ok: '✅ Dentro da meta — restam',
    sim_title: 'Simulação',
    sim_subtitle: 'Calcule o impacto e o custo de uma atividade. Atualiza sozinho.',
    sim_atividade: 'Atividade',
    sim_atividade_ph: 'Ex.: Banho de 15min',
    sim_consumo: 'Consumo',
    sim_criar: '+ Criar simulação',
    sim_resumo: 'Resumo',
    sim_total: 'Total estimado',
    sim_empty: 'Nenhuma simulação ainda.',
    sim_delete_aria: 'Deletar simulação',
    ins_title: 'Insights',
    ins_subtitle: 'Projeções, comparativo regional e recomendações da IA.',
    ins_janela: 'Janela analisada',
    ins_projecao: 'Projeção',
    ins_months: 'meses',
    ins_update: 'Atualizar',
    ins_empty: 'Ainda não há dados suficientes para gerar insights.',
    ins_forecast: 'Previsão total',
    ins_analyzed: 'meses analisados',
    ins_projected: 'meses projetados',
    ins_by_category: 'Por categoria',
    ins_last_month: 'último mês',
    ins_projected_label: 'projetado',
    ins_analyzing: 'Analisando…',
    ins_ask_ai: '🤖 Pedir análise IA',
    ins_generating_pdf: 'Gerando PDF…',
    ins_download_pdf: '📄 Baixar PDF',
    ins_ai_analysis: 'Análise da IA',
    ins_urgency: 'Urgência',
    ins_diagnosis: '📋 Diagnóstico Geral',
    ins_savings: '💰 Economia estimada:',
    ins_recommendations: '💡 Recomendações',
    per_title: 'Perfil',
    per_subtitle: 'Gerencie seus dados de conta.',
    per_nome: 'Nome',
    per_email: 'Email',
    per_cidade: 'Cidade',
    per_senha: 'Nova senha (opcional)',
    per_save: 'Salvar alterações',
    per_logout: 'Sair',
    per_delete: 'Excluir conta',
    per_updated: 'Perfil atualizado!',
    per_save_error: 'Não foi possível salvar.',
    per_delete_confirm: 'Excluir conta permanentemente? Essa ação não pode ser desfeita.',
    per_delete_error: 'Não foi possível excluir.',
    map_title: 'Pontos de reciclagem',
    map_near: 'Próximos a você',
    map_default: 'Mostrando pontos da região central.',
    map_empty: 'Nenhum ponto encontrado.',
    map_point: 'Ponto de coleta',
    map_routes: 'Rotas',
    con_delete_aria: 'Deletar',
  },

  'en-US': {
    nav_home:        'Home',
    nav_consumo:     'Usage',
    nav_simular:     'Simulate',
    nav_graficos:    'Charts',
    nav_insights:    'Insights',
    nav_mapa:        'Map',
    nav_config:      'Settings',

    menu_hi:         'Hello,',
    menu_impact:     'Your impact, in real time',
    menu_updated:    'Auto-updated every 10s.',
    menu_consumos:   'Entries',
    menu_simulacoes: 'Simulations',
    menu_gasto:      'Total accumulated cost',
    menu_metas:      'Goals',
    menu_ver_todas:  'View all →',
    menu_sem_meta:   'No goals created',
    menu_sem_meta_sub: 'Set spending limits and track your progress',
    menu_atalhos:    'Shortcuts',
    menu_tile_consumo:   'Usage',
    menu_tile_consumo_s: 'Log your expenses',
    menu_tile_metas:     'Goals',
    menu_tile_metas_s:   'Set limits',
    menu_tile_simular:   'Simulate',
    menu_tile_simular_s: 'Calculate impacts',
    menu_tile_graficos:  'Charts',
    menu_tile_graficos_s:'View trends',
    menu_tile_insights:  'Insights',
    menu_tile_insights_s:'AI recommendations',
    menu_tile_mapa:      'Map',
    menu_tile_mapa_s:    'Recycling points',
    menu_tile_perfil:    'Profile',
    menu_tile_perfil_s:  'Edit info',

    con_title:       'Usage',
    con_subtitle:    'Log and track your consumption.',
    con_tipo:        'Type',
    con_gasto:       'Cost (R$)',
    con_data:        'Date',
    con_meta:        'Link to a goal',
    con_meta_opt:    'optional',
    con_sem_meta:    '— No goal linked —',
    con_metas_tipo:  'Goals for',
    con_outras_metas:'Other goals',
    con_sem_metas_msg:'No goals yet. Create one in Goals 🎯',
    con_add_btn:     '+ Add entry',
    con_hist:        'History',
    con_vazio:       'No entries yet.\nCreate your first one above ☝️',

    settings:        '⚙️ Settings',
    subtitle:        'Personalize your EcoTotally experience.',
    profile:         'Profile',
    viewProfile:     'View my profile',
    appearance:      '🎨 Appearance',
    appDesc:         'Choose how the app should look.',
    light:           'Light',
    dark:            'Dark',
    system:          'System',
    reduceAnim:      'Reduce animations',
    notifications:   '🔔 Notifications',
    alertsLabel:     'Consumption & goal alerts',
    preferences:     '🌐 Preferences',
    language:        'Language',
    energyUnit:      'Energy unit',
    dataReports:     '📄 Data & reports',
    dataDesc:        'Download your full PDF report or clear local cache.',
    downloadPdf:     '📄 Download report (PDF)',
    generatingPdf:   'Generating PDF…',
    clearCache:      '🧹 Clear app cache',
    about:           'ℹ️ About',
    version:         'Version',
    support:         'Support',
    privacy:         'Privacy policy',
    terms:           'Terms of use',
    view:            'View',
    account:         '🚪 Account',
    logout:          'Sign out',
    themeUpdated:    'Theme updated.',
    reportDownloaded:'Report downloaded successfully.',
    cacheCleared:    'Cache cleared.',
    confirmCache:    'Clear app cache? Your settings will be kept, but you may need to sign in again.',
    // páginas principais
    g_title: 'Charts',
    g_subtitle: 'View usage and simulations by category.',
    g_consumos_tab: '📊 Usage',
    g_simulacoes_tab: '⚡ Simulations',
    g_empty_consumos: 'No usage entries yet. Add some to see charts.',
    g_total_geral: 'Grand total',
    g_records: 'records',
    g_por_categoria: 'By category',
    g_tendencia_mensal: 'Monthly trend',
    g_empty_simulacoes: 'No simulations yet. Create one in Simulation ⚡',
    g_custo_total_simulado: 'Total simulated cost',
    g_simulacoes: 'simulations',
    g_por_tipo: 'By type',
    meta_title: 'Goals',
    meta_subtitle: 'Set spending limits and track progress in real time.',
    meta_new_aria: 'New goal',
    meta_edit: 'Edit goal',
    meta_new: 'New goal',
    meta_close_aria: 'Close form',
    meta_tipo: 'Type',
    meta_objetivo: 'Target value (R$)',
    meta_inicio: 'Start',
    meta_fim: 'End',
    meta_save: '💾 Save goal',
    meta_empty: 'No goals created yet.',
    meta_empty_sub: 'Create the first one with the + button 👆',
    meta_edit_aria: 'Edit goal',
    meta_delete_aria: 'Delete goal',
    meta_days_left: 'd left',
    meta_acumulado: 'Accumulated',
    meta_objetivo_label: 'Target',
    meta_over: '⚠️ Goal exceeded by',
    meta_attention: '🟡 Warning: missing',
    meta_to_limit: 'to the limit',
    meta_ok: '✅ Within goal — remaining',
    sim_title: 'Simulation',
    sim_subtitle: 'Calculate the impact and cost of an activity. Auto-updates.',
    sim_atividade: 'Activity',
    sim_atividade_ph: 'Ex.: 15-min shower',
    sim_consumo: 'Usage',
    sim_criar: '+ Create simulation',
    sim_resumo: 'Summary',
    sim_total: 'Estimated total',
    sim_empty: 'No simulations yet.',
    sim_delete_aria: 'Delete simulation',
    ins_title: 'Insights',
    ins_subtitle: 'Forecasts, regional comparison and AI recommendations.',
    ins_janela: 'Analysis window',
    ins_projecao: 'Forecast',
    ins_months: 'months',
    ins_update: 'Update',
    ins_empty: 'There is not enough data to generate insights yet.',
    ins_forecast: 'Total forecast',
    ins_analyzed: 'months analisados',
    ins_projected: 'months projecteds',
    ins_by_category: 'By category',
    ins_last_month: 'last month',
    ins_projected_label: 'projected',
    ins_analyzing: 'Analyzing…',
    ins_ask_ai: '🤖 Ask AI analysis',
    ins_generating_pdf: 'Generating PDF…',
    ins_download_pdf: '📄 Download PDF',
    ins_ai_analysis: 'AI analysis',
    ins_urgency: 'Urgency',
    ins_diagnosis: '📋 General diagnosis',
    ins_savings: '💰 Estimated savings:',
    ins_recommendations: '💡 Recommendations',
    per_title: 'Profile',
    per_subtitle: 'Manage your account data.',
    per_nome: 'Name',
    per_email: 'Email',
    per_cidade: 'City',
    per_senha: 'New password (optional)',
    per_save: 'Save changes',
    per_logout: 'Sign out',
    per_delete: 'Delete account',
    per_updated: 'Profile atualizado!',
    per_save_error: 'Could not save.',
    per_delete_confirm: 'Delete account permanentemente? Essa ação não pode ser desfeita.',
    per_delete_error: 'Could not delete.',
    map_title: 'Recycling points',
    map_near: 'Near you',
    map_default: 'Showing points in the central region.',
    map_empty: 'No points found.',
    map_point: 'Collection point',
    map_routes: 'Routes',
    con_delete_aria: 'Delete',
  },

  'es-ES': {
    nav_home:        'Inicio',
    nav_consumo:     'Consumo',
    nav_simular:     'Simular',
    nav_graficos:    'Gráficos',
    nav_insights:    'Insights',
    nav_mapa:        'Mapa',
    nav_config:      'Config',

    menu_hi:         '¡Hola,',
    menu_impact:     'Tu impacto, en tiempo real',
    menu_updated:    'Actualizado automáticamente cada 10s.',
    menu_consumos:   'Consumos',
    menu_simulacoes: 'Simulaciones',
    menu_gasto:      'Gasto total acumulado',
    menu_metas:      'Metas',
    menu_ver_todas:  'Ver todas →',
    menu_sem_meta:   'Ninguna meta creada',
    menu_sem_meta_sub: 'Define límites de gasto y sigue tu progreso',
    menu_atalhos:    'Accesos rápidos',
    menu_tile_consumo:   'Consumo',
    menu_tile_consumo_s: 'Registra tus gastos',
    menu_tile_metas:     'Metas',
    menu_tile_metas_s:   'Define límites',
    menu_tile_simular:   'Simular',
    menu_tile_simular_s: 'Calcula impactos',
    menu_tile_graficos:  'Gráficos',
    menu_tile_graficos_s:'Visualiza tendencias',
    menu_tile_insights:  'Insights',
    menu_tile_insights_s:'Recomendaciones IA',
    menu_tile_mapa:      'Mapa',
    menu_tile_mapa_s:    'Puntos de reciclaje',
    menu_tile_perfil:    'Perfil',
    menu_tile_perfil_s:  'Editar datos',

    con_title:       'Consumo',
    con_subtitle:    'Registra y controla tus consumos.',
    con_tipo:        'Tipo',
    con_gasto:       'Gasto (R$)',
    con_data:        'Fecha',
    con_meta:        'Vincular a una meta',
    con_meta_opt:    'opcional',
    con_sem_meta:    '— Sin meta vinculada —',
    con_metas_tipo:  'Metas de',
    con_outras_metas:'Otras metas',
    con_sem_metas_msg:'Aún no hay metas. Crea una en Metas 🎯',
    con_add_btn:     '+ Agregar consumo',
    con_hist:        'Historial',
    con_vazio:       'Ningún consumo registrado.\nCrea el primero arriba ☝️',

    settings:        '⚙️ Configuración',
    subtitle:        'Personaliza tu experiencia en EcoTotally.',
    profile:         'Perfil',
    viewProfile:     'Ver mi perfil',
    appearance:      '🎨 Apariencia',
    appDesc:         'Elige cómo debe mostrarse la app.',
    light:           'Claro',
    dark:            'Oscuro',
    system:          'Sistema',
    reduceAnim:      'Reducir animaciones',
    notifications:   '🔔 Notificaciones',
    alertsLabel:     'Alertas de consumo y metas',
    preferences:     '🌐 Preferencias',
    language:        'Idioma',
    energyUnit:      'Unidad de energía',
    dataReports:     '📄 Datos e informes',
    dataDesc:        'Descarga tu informe completo en PDF o limpia la caché local.',
    downloadPdf:     '📄 Descargar informe (PDF)',
    generatingPdf:   'Generando PDF…',
    clearCache:      '🧹 Limpiar caché de la app',
    about:           'ℹ️ Acerca de',
    version:         'Versión',
    support:         'Soporte',
    privacy:         'Política de privacidad',
    terms:           'Términos de uso',
    view:            'Ver',
    account:         '🚪 Cuenta',
    logout:          'Cerrar sesión',
    themeUpdated:    'Tema actualizado.',
    reportDownloaded:'Informe descargado con éxito.',
    cacheCleared:    'Caché limpiada.',
    confirmCache:    '¿Limpiar caché de la app? Tu configuración se mantendrá, pero puede que tengas que iniciar sesión de nuevo.',
    // páginas principais
    g_title: 'Gráficos',
    g_subtitle: 'Visualiza consumos y simulaciones por categoría.',
    g_consumos_tab: '📊 Consumos',
    g_simulacoes_tab: '⚡ Simulaciones',
    g_empty_consumos: 'Aún no hay consumos. Registra algunos para ver los gráficos.',
    g_total_geral: 'Total general',
    g_registros: 'registros',
    g_por_categoria: 'Por categoría',
    g_tendencia_mensal: 'Tendencia mensual',
    g_empty_simulacoes: 'Aún no hay simulaciones. Crea una en Simulación ⚡',
    g_custo_total_simulado: 'Costo total simulado',
    g_simulacoes: 'simulaciones',
    g_por_tipo: 'Por tipo',
    meta_title: 'Metas',
    meta_subtitle: 'Define límites de gasto y sigue el progreso en tiempo real.',
    meta_new_aria: 'Nueva meta',
    meta_edit: 'Editar meta',
    meta_new: 'Nueva meta',
    meta_close_aria: 'Cerrar formulario',
    meta_tipo: 'Tipo',
    meta_objetivo: 'Valor objetivo (R$)',
    meta_inicio: 'Inicio',
    meta_fim: 'Fin',
    meta_save: '💾 Guardar meta',
    meta_empty: 'Aún no hay metas creadas.',
    meta_empty_sub: 'Crea la primera con el botón + 👆',
    meta_edit_aria: 'Editar meta',
    meta_delete_aria: 'Eliminar meta',
    meta_days_left: 'd restantes',
    meta_acumulado: 'Acumulado',
    meta_objetivo_label: 'Objetivo',
    meta_over: '⚠️ Meta superada en',
    meta_attention: '🟡 Atención: faltan',
    meta_to_limit: 'para el límite',
    meta_ok: '✅ Dentro de la meta — restan',
    sim_title: 'Simulación',
    sim_subtitle: 'Calcula el impacto y el costo de una actividad. Se actualiza solo.',
    sim_atividade: 'Actividad',
    sim_atividade_ph: 'Ej.: Baño de 15 min',
    sim_consumo: 'Consumo',
    sim_criar: '+ Crear simulación',
    sim_resumo: 'Resumen',
    sim_total: 'Total estimado',
    sim_empty: 'Aún no hay simulaciones.',
    sim_delete_aria: 'Eliminar simulación',
    ins_title: 'Insights',
    ins_subtitle: 'Proyecciones, comparativo regional y recomendaciones de IA.',
    ins_janela: 'Ventana analizada',
    ins_projecao: 'Proyección',
    ins_months: 'meses',
    ins_update: 'Actualizar',
    ins_empty: 'Aún no hay datos suficientes para generar insights.',
    ins_forecast: 'Previsión total',
    ins_analyzed: 'meses analizados',
    ins_projected: 'meses proyectados',
    ins_by_category: 'Por categoría',
    ins_last_month: 'último mes',
    ins_projected_label: 'proyectado',
    ins_analyzing: 'Analizando…',
    ins_ask_ai: '🤖 Pedir análisis IA',
    ins_generating_pdf: 'Generando PDF…',
    ins_download_pdf: '📄 Descargar PDF',
    ins_ai_analysis: 'Análisis de IA',
    ins_urgency: 'Urgencia',
    ins_diagnosis: '📋 Diagnóstico general',
    ins_savings: '💰 Ahorro estimado:',
    ins_recommendations: '💡 Recomendaciones',
    per_title: 'Perfil',
    per_subtitle: 'Gestiona los datos de tu cuenta.',
    per_nome: 'Nombre',
    per_email: 'Email',
    per_cidade: 'Ciudad',
    per_senha: 'Nueva contraseña (opcional)',
    per_save: 'Guardar cambios',
    per_logout: 'Salir',
    per_delete: 'Eliminar cuenta',
    per_updated: '¡Perfil actualizado!',
    per_save_error: 'No fue posible guardar.',
    per_delete_confirm: 'Eliminar cuenta permanentemente? Essa ação não pode ser desfeita.',
    per_delete_error: 'No fue posible eliminar.',
    map_title: 'Puntos de reciclaje',
    map_near: 'Cerca de ti',
    map_default: 'Mostrando puntos de la región central.',
    map_empty: 'No se encontraron puntos.',
    map_point: 'Punto de recolección',
    map_routes: 'Rutas',
    con_delete_aria: 'Eliminar',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  private _lang = signal<Lang>(this.loadLang());

  readonly lang = this._lang.asReadonly();

  /** Traduz uma chave. Fallback para pt-BR se não achar. */
  readonly t = computed(() => {
    const dict = DICT[this._lang()] ?? DICT['pt-BR'];
    return (key: string) => dict[key] ?? DICT['pt-BR'][key] ?? key;
  });

  setLang(lang: Lang): void {
    this._lang.set(lang);
    document.documentElement.setAttribute('lang', lang);
    try { localStorage.setItem(LANG_KEY, lang); } catch {}
  }

  private loadLang(): Lang {
    try {
      const fromPrefs = JSON.parse(localStorage.getItem(PREFS_KEY) ?? '{}')?.idioma;
      if (fromPrefs && DICT[fromPrefs as Lang]) return fromPrefs as Lang;
      const fromKey = localStorage.getItem(LANG_KEY) as Lang;
      if (fromKey && DICT[fromKey]) return fromKey;
    } catch {}
    return 'pt-BR';
  }
}
